package com.disser.kraken.ui.theme

import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Shapes
import androidx.compose.material3.darkColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

val LocalKrakenThemeTokens = staticCompositionLocalOf {
    KrakenThemePreset.DEFAULT.tokens()
}

private val QuietGraphiteScheme = darkColorScheme(
    primary = KrakenPrimary,
    onPrimary = KrakenOnPrimary,
    primaryContainer = Color(0xFF123C40),
    onPrimaryContainer = Color(0xFFC4F4F0),
    secondary = KrakenSecondary,
    onSecondary = Color(0xFF08233F),
    secondaryContainer = Color(0xFF233447),
    onSecondaryContainer = Color(0xFFD8E7FF),
    tertiary = KrakenTertiary,
    onTertiary = Color(0xFF2E1B00),
    tertiaryContainer = Color(0xFF46351F),
    onTertiaryContainer = Color(0xFFFFDFAF),
    error = KrakenError,
    onError = Color(0xFF3F0707),
    errorContainer = Color(0xFF4E2020),
    onErrorContainer = Color(0xFFFFD7D4),
    background = KrakenBackground,
    onBackground = Color(0xFFE5E8EB),
    surface = KrakenSurface,
    onSurface = Color(0xFFE5E8EB),
    surfaceVariant = KrakenSurfaceHigh,
    onSurfaceVariant = Color(0xFFB7C1C9),
    outline = Color(0xFF56616B),
    outlineVariant = Color(0xFF252C35),
)

private val LiquidGlassScheme = darkColorScheme(
    primary = Color(0xFF5DE7FF),
    onPrimary = Color(0xFF002026),
    primaryContainer = Color(0xFF143848),
    onPrimaryContainer = Color(0xFFC5F3FF),
    secondary = Color(0xFF9CE3D7),
    onSecondary = Color(0xFF003731),
    secondaryContainer = Color(0xFF123A42),
    onSecondaryContainer = Color(0xFFBCECE5),
    tertiary = Color(0xFFC6B7FF),
    onTertiary = Color(0xFF24134B),
    tertiaryContainer = Color(0xFF352B59),
    onTertiaryContainer = Color(0xFFE5DEFF),
    error = KrakenError,
    onError = Color(0xFF690005),
    background = Color(0xFF061013),
    onBackground = Color(0xFFE2E8EA),
    surface = Color(0xFF101A1F),
    onSurface = Color(0xFFE2E8EA),
    surfaceVariant = Color(0xFF1A2A31),
    onSurfaceVariant = Color(0xFFC3CDD1),
    outline = Color(0xFF83949B),
    outlineVariant = Color(0xFF32434B),
)

private val AbyssScheme = darkColorScheme(
    primary = Color(0xFF23D5C3),
    onPrimary = Color(0xFF00201D),
    primaryContainer = Color(0xFF063B4A),
    onPrimaryContainer = Color(0xFFB7F3EA),
    secondary = Color(0xFFD4B15F),
    onSecondary = Color(0xFF241A00),
    secondaryContainer = Color(0xFF443514),
    onSecondaryContainer = Color(0xFFFFE2A2),
    tertiary = Color(0xFF7BB7FF),
    onTertiary = Color(0xFF00284B),
    tertiaryContainer = Color(0xFF133657),
    onTertiaryContainer = Color(0xFFD4E4FF),
    error = KrakenError,
    onError = Color(0xFF690005),
    background = Color(0xFF030914),
    onBackground = Color(0xFFE0E6F0),
    surface = Color(0xFF071423),
    onSurface = Color(0xFFE0E6F0),
    surfaceVariant = Color(0xFF0D2235),
    onSurfaceVariant = Color(0xFFC1C9D4),
    outline = Color(0xFF788799),
    outlineVariant = Color(0xFF2A3D51),
)

private val SignalCleanScheme = darkColorScheme(
    primary = Color(0xFF7AC7FF),
    onPrimary = Color(0xFF00344F),
    primaryContainer = Color(0xFF15384C),
    onPrimaryContainer = Color(0xFFD0EAFF),
    secondary = Color(0xFFA8C7FA),
    onSecondary = Color(0xFF0B305F),
    secondaryContainer = Color(0xFF26384D),
    onSecondaryContainer = Color(0xFFD6E3FF),
    tertiary = Color(0xFFC1C7D0),
    onTertiary = Color(0xFF2B3138),
    tertiaryContainer = Color(0xFF343B45),
    onTertiaryContainer = Color(0xFFE0E6EE),
    error = KrakenError,
    onError = Color(0xFF690005),
    background = Color(0xFF090B0F),
    onBackground = Color(0xFFE2E2E8),
    surface = Color(0xFF12161C),
    onSurface = Color(0xFFE2E2E8),
    surfaceVariant = Color(0xFF20262E),
    onSurfaceVariant = Color(0xFFC5CAD2),
    outline = Color(0xFF8B919A),
    outlineVariant = Color(0xFF3A414A),
)

private val CompactMessengerScheme = darkColorScheme(
    primary = Color(0xFF58C7F3),
    onPrimary = Color(0xFF003545),
    primaryContainer = Color(0xFF173847),
    onPrimaryContainer = Color(0xFFC2EFFF),
    secondary = Color(0xFF88D4C3),
    onSecondary = Color(0xFF00372F),
    secondaryContainer = Color(0xFF1C3B40),
    onSecondaryContainer = Color(0xFFB9EADD),
    tertiary = Color(0xFFFFC978),
    onTertiary = Color(0xFF432C00),
    tertiaryContainer = Color(0xFF4D3A16),
    onTertiaryContainer = Color(0xFFFFDFA5),
    error = KrakenError,
    onError = Color(0xFF690005),
    background = Color(0xFF071117),
    onBackground = Color(0xFFE0E7EA),
    surface = Color(0xFF0F1C24),
    onSurface = Color(0xFFE0E7EA),
    surfaceVariant = Color(0xFF182B35),
    onSurfaceVariant = Color(0xFFC2CED4),
    outline = Color(0xFF82939C),
    outlineVariant = Color(0xFF30444E),
)

private val AmoledBlackScheme = darkColorScheme(
    primary = Color(0xFF20D7D2),
    onPrimary = Color(0xFF001F1F),
    primaryContainer = Color(0xFF063332),
    onPrimaryContainer = Color(0xFFC0FFFB),
    secondary = Color(0xFF8FDAD4),
    onSecondary = Color(0xFF003735),
    secondaryContainer = Color(0xFF123735),
    onSecondaryContainer = Color(0xFFC5F4EF),
    tertiary = Color(0xFFFFCB7B),
    onTertiary = Color(0xFF3F2D00),
    tertiaryContainer = Color(0xFF3B2C10),
    onTertiaryContainer = Color(0xFFFFE2AA),
    error = KrakenError,
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF4E1418),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color.Black,
    onBackground = Color(0xFFE7EDEE),
    surface = Color.Black,
    onSurface = Color(0xFFE7EDEE),
    surfaceVariant = Color(0xFF101415),
    onSurfaceVariant = Color(0xFFC1C8C9),
    outline = Color(0xFF7F8A8B),
    outlineVariant = Color(0xFF242A2B),
)

private val ResearchConsoleScheme = darkColorScheme(
    primary = Color(0xFF88E36A),
    onPrimary = Color(0xFF0B3600),
    primaryContainer = Color(0xFF183B18),
    onPrimaryContainer = Color(0xFFC8F7BA),
    secondary = Color(0xFF77D7C8),
    onSecondary = Color(0xFF003730),
    secondaryContainer = Color(0xFF173B37),
    onSecondaryContainer = Color(0xFFB1ECE2),
    tertiary = Color(0xFFD5B45F),
    onTertiary = Color(0xFF281D00),
    tertiaryContainer = Color(0xFF433614),
    onTertiaryContainer = Color(0xFFFFE1A0),
    error = KrakenError,
    onError = Color(0xFF690005),
    background = Color(0xFF050806),
    onBackground = Color(0xFFE0E7DD),
    surface = Color(0xFF0D160F),
    onSurface = Color(0xFFE0E7DD),
    surfaceVariant = Color(0xFF172419),
    onSurfaceVariant = Color(0xFFC2CEC0),
    outline = Color(0xFF83927F),
    outlineVariant = Color(0xFF334432),
)

fun KrakenThemePreset.tokens(): KrakenThemeTokens =
    when (this) {
        KrakenThemePreset.KRAKEN_DARK -> KrakenThemeTokens(
            colorScheme = QuietGraphiteScheme,
            cardRadius = 16.dp,
            controlRadius = 8.dp,
            screenPadding = 14.dp,
            cardSpacing = 12.dp,
            cardContentPaddingHorizontal = 10.dp,
            cardContentPaddingVertical = 8.dp,
            contentSpacing = 5.dp,
            listRowMinHeight = 50.dp,
            listRowPaddingHorizontal = 10.dp,
            listRowPaddingVertical = 7.dp,
            listRowGap = 9.dp,
            avatarSize = 30.dp,
            borderWidth = 1.dp,
            densityMode = densityMode,
            surfaceStyle = surfaceStyle,
        )
        KrakenThemePreset.LIQUID_GLASS -> KrakenThemeTokens(
            colorScheme = LiquidGlassScheme,
            cardRadius = 26.dp,
            controlRadius = 18.dp,
            screenPadding = 20.dp,
            cardSpacing = 18.dp,
            cardContentPaddingHorizontal = 16.dp,
            cardContentPaddingVertical = 14.dp,
            contentSpacing = 9.dp,
            listRowMinHeight = 60.dp,
            listRowPaddingHorizontal = 14.dp,
            listRowPaddingVertical = 11.dp,
            listRowGap = 12.dp,
            avatarSize = 36.dp,
            borderWidth = 1.dp,
            densityMode = densityMode,
            surfaceStyle = surfaceStyle,
        )
        KrakenThemePreset.ABYSS -> KrakenThemeTokens(
            colorScheme = AbyssScheme,
            cardRadius = 24.dp,
            controlRadius = 16.dp,
            screenPadding = 18.dp,
            cardSpacing = 16.dp,
            cardContentPaddingHorizontal = 14.dp,
            cardContentPaddingVertical = 12.dp,
            contentSpacing = 8.dp,
            listRowMinHeight = 58.dp,
            listRowPaddingHorizontal = 13.dp,
            listRowPaddingVertical = 10.dp,
            listRowGap = 11.dp,
            avatarSize = 34.dp,
            borderWidth = 1.dp,
            densityMode = densityMode,
            surfaceStyle = surfaceStyle,
        )
        KrakenThemePreset.SIGNAL_CLEAN -> KrakenThemeTokens(
            colorScheme = SignalCleanScheme,
            cardRadius = 14.dp,
            controlRadius = 12.dp,
            screenPadding = 18.dp,
            cardSpacing = 14.dp,
            cardContentPaddingHorizontal = 12.dp,
            cardContentPaddingVertical = 10.dp,
            contentSpacing = 6.dp,
            listRowMinHeight = 54.dp,
            listRowPaddingHorizontal = 12.dp,
            listRowPaddingVertical = 8.dp,
            listRowGap = 10.dp,
            avatarSize = 32.dp,
            borderWidth = 1.dp,
            densityMode = densityMode,
            surfaceStyle = surfaceStyle,
        )
        KrakenThemePreset.COMPACT_MESSENGER -> KrakenThemeTokens(
            colorScheme = CompactMessengerScheme,
            cardRadius = 14.dp,
            controlRadius = 10.dp,
            screenPadding = 12.dp,
            cardSpacing = 8.dp,
            cardContentPaddingHorizontal = 9.dp,
            cardContentPaddingVertical = 7.dp,
            contentSpacing = 4.dp,
            listRowMinHeight = 46.dp,
            listRowPaddingHorizontal = 9.dp,
            listRowPaddingVertical = 6.dp,
            listRowGap = 8.dp,
            avatarSize = 28.dp,
            borderWidth = 1.dp,
            densityMode = densityMode,
            surfaceStyle = surfaceStyle,
        )
        KrakenThemePreset.AMOLED_BLACK -> KrakenThemeTokens(
            colorScheme = AmoledBlackScheme,
            cardRadius = 12.dp,
            controlRadius = 8.dp,
            screenPadding = 12.dp,
            cardSpacing = 9.dp,
            cardContentPaddingHorizontal = 10.dp,
            cardContentPaddingVertical = 8.dp,
            contentSpacing = 5.dp,
            listRowMinHeight = 48.dp,
            listRowPaddingHorizontal = 10.dp,
            listRowPaddingVertical = 7.dp,
            listRowGap = 8.dp,
            avatarSize = 30.dp,
            borderWidth = 1.dp,
            densityMode = densityMode,
            surfaceStyle = surfaceStyle,
        )
        KrakenThemePreset.RESEARCH_CONSOLE -> KrakenThemeTokens(
            colorScheme = ResearchConsoleScheme,
            cardRadius = 12.dp,
            controlRadius = 8.dp,
            screenPadding = 16.dp,
            cardSpacing = 11.dp,
            cardContentPaddingHorizontal = 10.dp,
            cardContentPaddingVertical = 8.dp,
            contentSpacing = 5.dp,
            listRowMinHeight = 48.dp,
            listRowPaddingHorizontal = 10.dp,
            listRowPaddingVertical = 7.dp,
            listRowGap = 8.dp,
            avatarSize = 28.dp,
            borderWidth = 1.dp,
            densityMode = densityMode,
            surfaceStyle = surfaceStyle,
        )
    }

@Composable
fun KrakenTheme(
    preset: KrakenThemePreset = KrakenThemePreset.DEFAULT,
    content: @Composable () -> Unit,
) {
    val tokens = preset.tokens()
    CompositionLocalProvider(LocalKrakenThemeTokens provides tokens) {
        MaterialTheme(
            colorScheme = tokens.colorScheme,
            typography = MaterialTheme.typography,
            shapes = Shapes(
                extraSmall = RoundedCornerShape(tokens.controlRadius / 2),
                small = RoundedCornerShape(tokens.controlRadius),
                medium = RoundedCornerShape(tokens.cardRadius),
                large = RoundedCornerShape(tokens.cardRadius),
                extraLarge = RoundedCornerShape(tokens.cardRadius + 8.dp),
            ),
            content = content,
        )
    }
}
